# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test Export Newsletters

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 12am UTC every Sunday
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TARGET_URL: ${{ vars.TARGET_URL }}
  OUTPUT_DIR: ${{ vars.OUTPUT_DIR }}
  REPORT_DIR: ${{ vars.REPORT_DIR }}
  TARGET_REGEX: ${{ vars.TARGET_REGEX }}
  TARGET_ELEMENT: ${{ vars.TARGET_ELEMENT }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: make install-tools

    - name: Test Export Newsletters
      run: make test

